
metricList = ['mort', 'icu', 'hosp', 'hospTime', 'sympt', 'infect']
metricListRaw = {'die' : 'mort', 'icu' : 'icu', 'hosp' : 'hosp', 'hospTime' : 'hospTime', 'sympt' : 'sympt'}

cohortMetricList = ['halyAcute', 'halyDeath', 'halyLong']
singleMetricList = [
	'costDeathAverted',
	'costAcute',
	'costTesting',
	'costVaccine',
	'costVaccineFixed',
	'costMask',
	'costMaskFixed',
	'costGdp',
	'costTotalHealth',
	'nmbLow',
	'nmbMed',
	'nmbHigh',
	'nmbLowNoGdp',
	'nmbMedNoGdp',
	'nmbHighNoGdp',
	'halyTotalAcute',
	'halyTotalDeath',
	'halyTotalLong',
	'halyTotalTotal',
	'totStage2',
	'totStage3',
	'totStage4',
	'totStage5',
	'totInfect',
	'totSympt',
	'totHosp',
	'totIcu',
	'totDeath',
	'totHospTime',
	'totIcuTime',
	'mid_costDeathAverted',
	'mid_costAcute',
	'mid_costTesting',
	'mid_costVaccine',
	'mid_costVaccineFixed',
	'mid_costMask',
	'mid_costMaskFixed',
	'mid_costGdp',
	'mid_costTotalHealth',
	'mid_nmbLow',
	'mid_nmbMed',
	'mid_nmbHigh',
	'mid_nmbLowNoGdp',
	'mid_nmbMedNoGdp',
	'mid_nmbHighNoGdp',
	'mid_halyTotalAcute',
	'mid_halyTotalDeath',
	'mid_halyTotalLong',
	'mid_halyTotalTotal',
	'mid_totStage2',
	'mid_totStage3',
	'mid_totStage4',
	'mid_totStage5',
	'mid_totInfect',
	'mid_totSympt',
	'mid_totHosp',
	'mid_totIcu',
	'mid_totDeath',
	'mid_totHospTime',
	'mid_totIcuTime',
]
stages = [1, 2, 3, 4, 5]
