
metricList = ['mort', 'icu', 'hosp', 'hospTime', 'sympt', 'infect']
metricListRaw = {'die' : 'mort', 'icu' : 'icu', 'hosp' : 'hosp', 'hospTime' : 'hospTime', 'sympt' : 'sympt'}

cohortMetricList = ['halyAcute', 'halyDeath', 'halyLong']
timefullMetrics = {
	'prevInfections' : {
		'length' : 9,
		'colName' : 'prevInfects',
	},
	'aggOutcome' : {
		'length' : 5,
		'colName' : 'outcome',
		#'doDaily' : True,
		'rename' : [
			'1_infections',
			'2_sympts',
			'3_hosps',
			'4_icus',
			'5_deaths',
		],
	},
	'hospUsage' : {
		'length' : 1,
		'colName' : 'hospUsage',
		#'doDaily' : True,
	},
	'aveImmuneVac' : {
		'length' : 6,
		'colName' : 'outcome',
		'aggMean' : True,
		'rename' : [
			'0_infectivity',
			'1_risk',
			'2_sympt',
			'3_hosp',
			'4_icu',
			'5_mortality',
		],
	},
	'aveImmuneNat' : {
		'length' : 6,
		'colName' : 'outcome',
		'aggMean' : True,
		'rename' : [
			'0_infectivity',
			'1_risk',
			'2_sympt',
			'3_hosp',
			'4_icu',
			'5_mortality',
		],
	
	},
	'aveImmuneAll' : {
		'length' : 6,
		'colName' : 'outcome',
		'aggMean' : True,
		'rename' : [
			'0_infectivity',
			'1_risk',
			'2_sympt',
			'3_hosp',
			'4_icu',
			'5_mortality',
		],
	}
}

singleMetricList = [
	'costDeathAverted',
	'costAcute',
	'costLong',
	'costTesting',
	'costVaccine',
	'costVacDeliver',
	'costVaccineFixed',
	'costMask',
	'costMaskFixed',
	'costGdp',
	'costTotalHealth',
	'costTotalTotal',
	'nmbLow',
	'nmbMed',
	'nmbHigh',
	'nmbLowNoGdp',
	'nmbMedNoGdp',
	'nmbHighNoGdp',
	'halyTotalAcute',
	'halyTotalDeath',
	'halyTotalLong',
	'halyTotalTotal',
	'totStage2',
	'totStage3',
	'totStage4',
	'totStage5',
	'totInfect',
	'totSympt',
	'totHosp',
	'totIcu',
	'totDeath',
	'totHospTime',
	'totIcuTime',
	'hospDaysAbove500',
	'hospDaysAbove750',
	'hospDaysAbove1000',
	'hospDaysAbove1250',
	'hospDaysAbove1500',
	'hospDaysAbove1750',
	'hospDaysAbove2000',
	'costDeathAverted_uk',
	'halyTotalDeath_uk',
	'costTotalHealth_uk',
	'costTotalTotal_uk',
	'halyTotalTotal_uk',
	'nmbLow_uk',
	'nmbMed_uk',
	'nmbHigh_uk',
	'nmbLowNoGdp_uk',
	'nmbMedNoGdp_uk',
	'nmbHighNoGdp_uk',
	'prevInfect0',
	'prevInfect1',
	'prevInfect2',
	'prevInfect3',
	'prevInfect4',
	'prevInfect5',
	'prevInfect6',
	'prevInfect7',
	'prevInfect8',
	'mid_costDeathAverted',
	'mid_costAcute',
	'mid_costLong',
	'mid_costTesting',
	'mid_costVaccine',
	'mid_costVacDeliver',
	'mid_costVaccineFixed',
	'mid_costMask',
	'mid_costMaskFixed',
	'mid_costGdp',
	'mid_costTotalHealth',
	'mid_costTotalTotal',
	'mid_nmbLow',
	'mid_nmbMed',
	'mid_nmbHigh',
	'mid_nmbLowNoGdp',
	'mid_nmbMedNoGdp',
	'mid_nmbHighNoGdp',
	'mid_halyTotalAcute',
	'mid_halyTotalDeath',
	'mid_halyTotalLong',
	'mid_halyTotalTotal',
	'mid_totStage2',
	'mid_totStage3',
	'mid_totStage4',
	'mid_totStage5',
	'mid_totInfect',
	'mid_totSympt',
	'mid_totHosp',
	'mid_totIcu',
	'mid_totDeath',
	'mid_totHospTime',
	'mid_totIcuTime',
	'mid_hospDaysAbove500',
	'mid_hospDaysAbove750',
	'mid_hospDaysAbove1000',
	'mid_hospDaysAbove1250',
	'mid_hospDaysAbove1500',
	'mid_hospDaysAbove1750',
	'mid_hospDaysAbove2000',
	'mid_costDeathAverted_uk',
	'mid_halyTotalDeath_uk',
	'mid_costTotalHealth_uk',
	'mid_costTotalTotal_uk',
	'mid_nmbLow_uk',
	'mid_nmbMed_uk',
	'mid_nmbHigh_uk',
	'mid_nmbLowNoGdp_uk',
	'mid_nmbMedNoGdp_uk',
	'mid_nmbHighNoGdp_uk',
	'mid_halyTotalTotal_uk',
	'mid_prevInfect0',
	'mid_prevInfect1',
	'mid_prevInfect2',
	'mid_prevInfect3',
	'mid_prevInfect4',
	'mid_prevInfect5',
	'mid_prevInfect6',
	'mid_prevInfect7',
	'mid_prevInfect8',
	'sen_vacInfectReduct',
	'sen_vacWaneInfect',
	'sen_vacWaneHosp',
	'sen_recoverInfectReduct',
	'sen_recoverWane',
	'sen_maskEff',
	'sen_asymptTransmit',
	'sen_isoProp',
	'sen_ifr',
	'sen_icu',
	'sen_hosp',
	'sen_sympt',
	'sen_hospTime',
	'sen_icuTime',
	'sen_vacCur',
	'sen_vacTarget',
	'sen_vacMulti',
	'sen_vacPromote',
	'sen_vacOverhead',
	'sen_maskPerson',
	'sen_maskStorage',
	'sen_maskPromote',
	'sen_vacUptake',
	'sen_transmissDraw',
	'sen_isoComply',
	'sen_halyAcute',
	'sen_halyLong',
	'sen_halyDeath',
	'sen_costGdp',
	'sen_costTest',
	'sen_costLong',
	'sen_costDeath',
	'sen_costDoctor',
	'sen_costParacetamol',
	'sen_costVisitEr',
	'sen_costHospBed',
	'sen_costIcuBed',
]
stages = [1, 2, 3, 4, 5]
